### ISSUE TITLE
Sanity checks in CAA edits

### ISSUE THREAD

**Issue by ROpdebee** [ROpdebee/mb-userscripts#12]
https://chatlogs.metabrainz.org/brainzbot/musicbrainz/msg/4774758/

Spot and highlight shady things CAA edits.

- [x] Earliest release date in the release events is after the end of the voting period: Cover art may be incorrect
- [x] Square dimensions while packaging type is typically non-square (digipaks, digibook, book, gatefold (?), ...): Most likely wrong
- [x] Typical digital media dimensions (3000x3000, 1400x1400) on a physical release: Should be scrutinised to make sure the cover is the same as the physical release.
- [x] Non-front cover on a digital media release: Likely wrong
- [x] Track on a physical release: Non-sensical type
- [x] No types set: Non-ideal
- [x] Obi on non-JP releases: Likely wrong
- [x] Watermark type set: Non-ideal
- [x] Liner on non-Vinyl releases: Uncommon, but possible
- [ ] Non-matching barcodes: Maybe https://serratus.github.io/quaggaJS/ ?
- [x] Cover art on pseudo-releases
- [x] URLs in comments: Arguably shouldn't be there

**Comment by ROpdebee** [comment]
Skipping the barcode thing, probably it's somehow possible but Quagga leads to security exceptions for some reason.
Chrome and Edge apparently has a barcode detection API built-in, but not supported in Firefox, and there's probably little added benefit.

**Comment by kellnerd** [comment]
> Square dimensions while packaging type is typically non-square (digipaks, digibook, book, gatefold (?), ...): Most likely wrong

While this is true for packaging types like front and back, I found it quite amusing to see the warning message for square images of the medium itself, e.g. in [Edit #78526849](https://musicbrainz.org/edit/78526849). It would be great if you could also account for the image type :)

**Comment by ROpdebee** [comment]
Oops, bit of an oversight. Fixed! Thanks for the report.

**Comment by ROpdebee** [comment]
It might make sense for cassettes though... 🤔
