### ISSUE TITLE
Chrome version pattern

### ISSUE THREAD

**Issue by jesus2099** [ROpdebee/mb-userscripts#2]
Hi. ☺️
Could you use one of the 2 version schemes/patterns that works in 100% userscript engines?

Either [Chrome specs](https://developer.chrome.com/apps/manifest/version) that allow convenient `yyyy.m.d(.hm)` date versions like you already use, but you must remove your leading zeros (which [proved](https://github.com/jesus2099/konami-command/pull/1) to stop auto updates in some engine).

Or [SemVer](https://duckduckgo.com/?q=SemVer&t=vivaldi&ia=web) `x.y.z`, personally I don't like it as much.

**Comment by ROpdebee** [comment]
You'll probably know the answer to this: If you have a version like `2021.2.11.2` and update it to `2021.2.12` (like I did in https://github.com/ROpdebee/mb-userscripts/commit/af1fe2ba1dbe410476c1735d561ec3e874a5b15a), does this also break Chrome versioning?

**Comment by jesus2099** [comment]
No no, there is no problem with that.
The problem is (was?) only with 0 padded numbers and long numbers like `20210211` or `202102111835`(I used to use that).
