### ISSUE TITLE
[cover art uploader] Uncaught (in promise) TypeError: e.split(...).at is not a function

### ISSUE THREAD

**Issue by jesus2099** [ROpdebee/mb-userscripts#214]
I am on https://musicbrainz.org/release/6f2681d8-3a9e-3b45-b957-badc73649f96 trying to upload newly linked Discogs front cover:

> Uncaught (in promise) TypeError: e.split(...).at is not a function
> add-cover-art line 1 > scriptElement:104572:29695

Same error if I copy/paste image URL.
Same in beta MBS.

I am on Linux Debian 10, Firefox 78.15.0esr (64 bits).

**Comment by jesus2099** [comment]
For the record, there is no such issue in Windows 10, Vivaldi 4.3.2439.63 (Stable channel) (64 bits).
I will try the patched version on the other PC, and tell you. Thank you. :)

**Comment by jesus2099** [comment]
Wow, it's magic!
It works super great in Firefox 78 too, now!!!

**Comment by ROpdebee** [comment]
Awesome! There's a possibility that you'll still run into other ESNext APIs that are not available, since it seems like MBS uses an old version of the polyfills (and it could be VGMdb/a-tisket don't polyfill something we need). If so, let me know. It should get better once I add some automated tests for older browsers, but I still need to get started on that 😅

**Comment by jesus2099** [comment]
Thanks.
Yes, Vivaldi is always with recent Chromium.
I use Vivaldi and Firefox, depending on office or home PC.

**Comment by jesus2099** [comment]
Wow it apparently also works on Android 9 Firefox 68! 🕺💃

**Comment by jesus2099** [comment]
I have found [`array.at` documentation](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/at), now.
If you want to avoid polyfill, as you just want the last array element, you could simply use `.pop()`, I think:

```js
url.pathname.split('/').pop()
```

Instead of:

```js
url.pathname.split('/').at(-1)
```

**Comment by ROpdebee** [comment]
Thanks. Unfortunately there are two cases where we're using `.at(-2)`. We could of course just use `arr[arr.length - 2]` but we might have to include many more polyfills for older Firefox versions using Greasemonkey (see #224, basically, Greasemonkey scripts using `GM_*` functions run isolated from the page, so polyfills added by MB won't be available to the script). Depending on how I choose to handle those, I might leave the `Array.at` polyfill in.
