### ISSUE TITLE
Handle Spotify images without file extension

### ISSUE THREAD

**Issue by kellnerd** [ROpdebee/mb-userscripts#216]
It seems like Spotify no longer uses filename extensions for their cover art. The a-tisket seeder displays TLD and path as extension for Spotify images now (e.g. [CO/IMAGE/AB67616D0000B273B8FFC252C4575933EE3BAABD](https://atisket.pulsewidth.org.uk/?cached=00050087497163-d_268337782-s_3qBn8Lw72Fs6zWyA7yFrMn-i_1590946281)).

**Comment by kellnerd** [comment]
I guess reverting https://github.com/ROpdebee/mb-userscripts/commit/d6e7717a07e31cb9046b251345d2f3924b5a5503 would be the simplest solution.
Not sure whether it's worth the effort to detect the mimetype here just for Spotify images which are hopefully only rarely selected for seeding from a-tisket.

**Comment by ROpdebee** [comment]
Again one of those things an E2E test might've spotted.

Just reverting is probably fine. I think Spotify is always JPEG anyway, but I'm not sure how much effort it would take to hardcode that.
