### ISSUE TITLE
Upload covers directly from iTunes/Spotify/Discogs/... link

### ISSUE THREAD

**Issue by ROpdebee** [ROpdebee/mb-userscripts#23]
It would be really cool if I could paste in an Apple Music, Spotify, Amazon, Deezer, Discogs, … link into the pastebox of the CAA URL uploader, and it would grab all covers and insert them automatically.

It would be even cooler if it could just get the URLs from the release, instead of having to paste them.

Depends on #20.

**Comment by djl** [comment]
👍🏻 

A nice stopgap for now might be to allow pasting multiple whitespace-delimited URLs at once and have the script fetch them all.

**Comment by ROpdebee** [comment]
That's an interesting idea to keep in mind.

Another one would be to somehow be able to seed it through the release's URL, and for example add a link in atisket's post-submit screen to save a couple of clicks. Or add a right-click context menu action to seen <img> elements on other sites, but I'm not 100% sure that a userscript can do that, so it may require a browser extension instead.

It would even be technically possible to submit cover art edits directly from atisket or other sites from which we can find the correct MB release… But that could be a completely new userscript, or at the very least a rename of this one.

Suffice it to say: There are many innovative ways in which the cover art submission process could, and should, be improved.
