### ISSUE TITLE
Little typo in MB: Enhanced Cover Art Uploads

### ISSUE THREAD

**Issue by Fabe56** [ROpdebee/mb-userscripts#233]
Hi,
Just to report a little typo in the wording, [should be](https://musicbrainz.org/edit/84524388#note-84524388-3) "maximized".
Thanks.

**Comment by ROpdebee** [comment]
Thanks for the report. However, it's not a typo, ["maximised" is British English spelling](https://www.merriam-webster.com/dictionary/maximise) and not "lazy slang" like some clearly disgruntled people might claim. 🙂
