### ISSUE TITLE
Data URL

### ISSUE THREAD

**Issue by jesus2099** [ROpdebee/mb-userscripts#25]
I see some edits with data URL.
It breaks the MB page width.
I think data URL should no be included completely in the edit notes.
https://musicbrainz.org/edit/80219294
https://musicbrainz.org/edit/80219185

**Comment by ROpdebee** [comment]
I've noticed this too (same editor, I think). It should be fixed in 2021.6.7 (4f8802249ff1e8c8fc5706ae0d79da7a7669c0a9), which came out after these edits were made. If you still notice this on newer edits, please reopen.
