### ISSUE TITLE
Deduplicate edit notes generated by CAA URL uploader 

### ISSUE THREAD

**Issue by kellnerd** [ROpdebee/mb-userscripts#26]
Currently the _MB: Upload to CAA From URL_ message is [repeated for each URL](https://musicbrainz.org/edit/80414615) unless the user manually changes the generated edit note.
It would be great if the script could detect this and would append only the new URL in this case.
Depending on how you want to implement #23 it is going to be even more needed then.

**Comment by ROpdebee** [comment]
Untested and not the most elegant solution, but should do the trick.
