### ISSUE TITLE
Display cover art file extension/mimetype

### ISSUE THREAD

**Issue by kellnerd** [ROpdebee/mb-userscripts#27]
In addition to the file size it would be useful to know whether an image is a JPEG or a PNG.

**Comment by ROpdebee** [comment]
A simple way would be to use the format field provided by the IA in the metadata. I'll get to it eventually, but PRs most welcome.

**Comment by kellnerd** [comment]
Thanks, I could finally test it, but I had to delete the whole image cache first, otherwise the mimetypes were missing in too many (already cached) places where I would like to see them.
I don't know why, but I had to redo this a few times and restart my browser, because there was still an empty Indexed DB entry left which had caused the userscript to fail completely, before the cache was finally gone for good 😁
