### ISSUE TITLE
MB: Enhanced Cover Art Uploads Amazon problem

### ISSUE THREAD

**Issue by tigerman325** [ROpdebee/mb-userscripts#272]
The last few releases I've worked on no longer blow up any Amazon images to full size and is actually limited all of them to 500x?, below what they actually even show on the Amazon page. I can manually open all the images on the Amazon page and Image Max URL blows them up, so I can feed them per link, but when I click on the import from Amazon is when they don't show up larger than 500x? (keeps ratio, but limits to 500)

**Comment by kellnerd** [comment]
Indeed, Amazon has slightly changed their website and I am getting the fallback message now:
> Failed to extract Amazon images from the embedded JS, falling back to thumbnails

Unfortunately that message is only visible in the browser console until #81 has been resolved.
But at least the Amazon regression is very easy to fix.
