### ISSUE TITLE
Qobuz: API returns 404 when release is available

### ISSUE THREAD

**Issue by ROpdebee** [ROpdebee/mb-userscripts#335]
> Even before the script supported Qobuz I noticed that for a few releases the [API returns 404](https://beta.musicbrainz.org/collection/fa88d508-1e59-45a6-bd6c-53fcb8d06cf2) even though the release is still visible in the shop at least in the linked locale.
> Another [fresh example from the forum](https://community.metabrainz.org/t/a-multi-source-seeder-for-digital-releases/444000/454)

https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/44?u=ropdebee

I should at least investigate and see if I can figure something out, perhaps do a workaround in case it's frequent. IIRC we don't strictly need the Qobuz API except for goodies, and we still have the ID-based cover URL constructor from the original implementation, so we may as well put it to use. Or perhaps we're already using it as a backup, I can't remember 🙂

**Comment by tigerman325** [comment]
Is this related? I just tried to grab the image from the following Qobuz release. It returns "Failed to grab images: Failed to construct 'URL': Invalid URL" even though it's a valid URL & I was able to just right click on Qobuz page and grab via image URL that way. However, this release also has a booklet I was hoping to grab. Maybe that's causing the issue? See if we can get the booklet: https://www.qobuz.com/us-en/album/the-endless-river-pink-floyd/fy3ginyk9q1wa. Release: https://musicbrainz.org/release/dfcd5b88-a028-49e0-bc2a-08fbb866c97b/add-cover-art

**Comment by ROpdebee** [comment]
The API returns a 404 for me for that release, so it might be related. Unsure why it complains of a broken URL though… Does it "work" with the newest version? It might have something to do with the availability of streaming in different regions, since https://open.qobuz.com/album/fy3ginyk9q1wa redirects to the home page for me (because the API returns a 404).

**Comment by kellnerd** [comment]
> Failed to grab images: URL constructor: null is not a valid URL.

... is the error message I get using both v2022.1.2 and v2022.1.24. It happens during the goodie extraction:
https://github.com/ROpdebee/mb-userscripts/blob/0caf10c93680bf0ca08b547e6234b8a0f8547a66/src/mb_enhanced_cover_art_uploads/providers/qobuz.ts#L84

**Comment by kellnerd** [comment]
> does the open.qobuz.com link work for you?

Nope, it also redirects me to the home page.

**Comment by ROpdebee** [comment]
OK, the goodies in the response include video clips which don't have a URL, so those need to be filtered out:
```json
[
  {
    "id": 111507,
    "file_format_id": 52,
    "name": "Clip vidéo",
    "description": "Anisina",
    "url": null,
    "original_url": null
  },
  {
    "id": 111508,
    "file_format_id": 52,
    "name": "Clip vidéo",
    "description": "Untitled",
    "url": null,
    "original_url": null
  },
  {
    "id": 111509,
    "file_format_id": 52,
    "name": "Clip vidéo",
    "description": "Evrika (A)",
    "url": null,
    "original_url": null
  },
  {
    "id": 111510,
    "file_format_id": 52,
    "name": "Clip vidéo",
    "description": "Nervana",
    "url": null,
    "original_url": null
  },
  {
    "id": 111511,
    "file_format_id": 52,
    "name": "Clip vidéo",
    "description": "Allons-y",
    "url": null,
    "original_url": null
  },
  {
    "id": 111512,
    "file_format_id": 52,
    "name": "Clip vidéo",
    "description": "Evrika (B)",
    "url": null,
    "original_url": null
  },
  {
    "id": 111513,
    "file_format_id": 21,
    "name": "Livret Numérique",
    "description": "Pink Floyd - The Endless River",
    "url": "https://static.qobuz.com/goodies/31/000111513.pdf",
    "original_url": "https://static.qobuz.com/goodies/31/000111513.pdf"
  }
]
```

**Comment by ROpdebee** [comment]
On the topic of API 404s, it appears Qobuz is using the IP address of the requester to figure out their location, and returns a 404 if the album is not available in their location. The release posted above is available in the US, and with a US IP, the API will return the requested information. However, it's not available in Europe (https://www.qobuz.com/be-nl/album/the-endless-river-pink-floyd/fy3ginyk9q1wa is 404), and from a European IP, the API returns 404. It doesn't look like you can convince the Qobuz API that you're in a different country, except for using a proxy or VPN. The European release has a different ID (https://www.qobuz.com/be-nl/album/the-endless-river-pink-floyd/0825646184729). The API does work for this release in Europe, but not in the US.

**Comment by tigerman325** [comment]
It works now!! Thanks for the fix.
