### ISSUE TITLE
MB: QoL: Live recording comments issue with Washington, DC

### ISSUE THREAD

**Issue by tigerman325** [ROpdebee/mb-userscripts#338]
https://musicbrainz.org/release/1dbe6954-1d1c-4fe5-a9c2-be42d9baa404

On track 7 when using "live" seeding, for some reason it omitted "Washington". It left "live, 1971‐11‐16: Lisner Auditorium, DC, USA" in the comment. It should be "live, 1971‐11‐16: Lisner Auditorium, Washington, DC, USA"

**Comment by ROpdebee** [comment]
Hmm, it's because Washington DC is set as a subdivision, so the script thinks there's no city, just a state. I'll add an exception for DC.
