### ISSUE TITLE
Enhanced cover art uploads script fails with "Skipping <filename>: Cannot read properties of undefined (reading 'filename')"

### ISSUE THREAD

**Issue by atj** [ROpdebee/mb-userscripts#351]
The latest update to the userscript has completely broken functionality for me, any attempt to import an image results in errors like:

```
Skipping 500x500.jpg: Cannot read properties of undefined (reading 'filename')
```
The error console displays the following:

```
[mb_enhanced_cover_art_uploads] Searching for images in Deezer release…
instrument.js:102 [mb_enhanced_cover_art_uploads] Found 1 images in Deezer release
instrument.js:102 [mb_enhanced_cover_art_uploads] Skipping 500x500.jpg TypeError: Cannot read properties of undefined (reading 'filename')
    at MB： Enhanced Cover A…oads.user.js:106311
    at l (MB： Enhanced Cover A…oads.user.js:104504)
```

The first line in the stack trace points to:

https://github.com/ROpdebee/mb-userscripts/blob/98f99f6c06c7a293b5685df6c23131bf291cb8c9/src/mb_enhanced_cover_art_uploads/fetch.ts#L80

Entering a URL in the input box results in the same error.

I'm running:

- Brave v1.33.106-1 on Linux
- Violentmonkey v2.13.0
- MB: Enhanced Cover Art Uploads v2021.12.29.3

**Comment by kellnerd** [comment]
@atj please install and test the preview from https://github.com/ROpdebee/mb-userscripts/pull/352#issuecomment-1003003221 which should fix the issue.

**Comment by atj** [comment]
Works for me, thanks for the quick fix!
