### ISSUE TITLE
Drop IMU exceptions which are no longer necessary

### ISSUE THREAD

**Issue by kellnerd** [ROpdebee/mb-userscripts#392]
We can probably remove our custom maximisation logic for Apple Music by now, IMU has implemented support for source images in https://github.com/qsniyg/maxurl/commit/56e0fce886bd328e8a155fc69dd62ff954fa0053 (but I have not tested it yet).

Same for 7digital, native support has been added in https://github.com/qsniyg/maxurl/commit/9e50ab7dff78df686b4422dcbcb4cf418ba5df22.

**Comment by ROpdebee** [comment]
Hmm, IMU always tries an AM `/source` URL first, which I think exists only old-style iTunes cover URLs, not for new-style AM image URLs. So for AM releases, the script will always warn with "Skipping maximised candidate…" first, which is not ideal. So we might still need an exception for IMU just to reorder the candidates.
