### ISSUE TITLE
Amazon audiobooks causing trouble again

### ISSUE THREAD

**Issue by kellnerd** [ROpdebee/mb-userscripts#400]
https://www.amazon.fr/gp/product/207055998X (an audiobook on CD) fulfills both the `PHYSICAL_AUDIOBOOK_PAGE_QUERY` and the `AUDIBLE_PAGE_QUERY` (because a digital media version is also available on Audible). Since the `AUDIBLE_PAGE_QUERY` condition comes first, the extraction of the cover images fails: The Audible release has a different ASIN, so the attempt to find the non-existing `/hz/audible/mlp/mfpdp/` page of the CD leads to a redirect to the product page, where the `AUDIBLE_FRONT_IMAGE_QUERY` does not work of course.
Changing the order of the conditions fixes this case but breaks our existing Audible unit test.
I don't have time to look into it right now, but we need better page queries if we don't want to introduce a fallback mechanism again.

**Comment by ROpdebee** [comment]
Perhaps `#productLogo > img[alt="Audible Logo"]` or just `#audibleProductTitle`? The former matches the Audible logo next to the product title, the latter matches the product title itself. Neither are present present on your product but matches the one from the tests and the audiobook version of your example. Alternatively, we could reuse the existing query but change it to `.a-button-selected .audible_mm_title` so we only match if the Audible button is the highlighted one.
