### ISSUE TITLE
a-tisket seeder for Apple Music sometimes fails with status 429

### ISSUE THREAD

**Issue by kellnerd** [ROpdebee/mb-userscripts#438]
https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/57

> On a rare occasion I saw a 429 from Apple. This caused the link for cover art seeding not to be added. Perhaps the script could gracefully retry or show a manual retry option?
> https://atisket.pulsewidth.org.uk/?spf_id=1WRqanANwPz8JyH0p78IPh
```
9999x9999-100.jpg:1          Failed to load resource: the server responded with a status of 429 ()
MB： Enhanced Cover Art Uploads.user.js:105074 [mb_enhanced_cover_art_uploads] Failed to add seed links to some cover art
onError @ MB： Enhanced Cover Art Uploads.user.js:105074
```

https://github.com/ROpdebee/mb-userscripts/blob/fa62e412476222c5dad9c73bf22b2ff856c99d78/src/mb_enhanced_cover_art_uploads/seeding/atisket.tsx#L76

Has to be related to the fetching of the image's dimensions since the insertion of the seed link itself should not cause an additional request to Apple's servers. The HTTP error makes the whole function fail, maybe these two features should be separated to avoid this.
Probably not worth to fix the underlying issue right now, automatic retries could be part of the refactoring of [mb_caa_dimensions](https://github.com/ROpdebee/mb-userscripts/blob/main/mb_caa_dimensions.user.js) into TS modules instead.

**Comment by ROpdebee** [comment]
I think there's some function in the TS modules that allows for automated retrying with backoff, so fixing the underlying issue should indeed be part of a rewrite.

Would it make sense to move the image dimensions functionality on atisket to that script in its entirety? Ideally those results would be cached too, so I'd need to check whether we can share an IndexedDB cache between scripts.
