### ISSUE TITLE
Incompatibility with Opera/Tampermonkey

### ISSUE THREAD

**Issue by ROpdebee** [ROpdebee/mb-userscripts#51]
Reported by @Lotheric on IRC

```
22:13 <Lotheric> ROpdebee, the new enhanced CAA script doesn't seem to work with Tampermonkey/Opera for me
22:13 <Lotheric> v2021.9.23.3
22:14 <Lotheric> w/ Opera 79.0.4143.66
22:14 <Lotheric> and Tampermonkey for Opera v4.13.6138
22:14 <Lotheric> previous one was working for me
22:20 <Lotheric> something seems to appear and disappear almost immediately
22:20 <Lotheric> probably a problem du to React?
```

@Lotheric: If you've managed to figure out more info, please add :)

**Comment by ROpdebee** [comment]
I cannot reproduce this on a fresh install of Opera 79.0.4143.50 (there is no .66 for macOS, apparently) and Tampermonkey for Opera v4.13.6138 with 2021.9.23.3 or 2021.9.24.

> something seems to appear and disappear almost immediately

I see that too, but I think those are the messages that show up when the image is being uploaded (stuff like "Requesting signature..." etc.). It might flash up for a second if MB's JS takes a bit too long to load. That should all be unrelated to this script though, since it doesn't really touch anything in there.

I'm a bit stumped as to what could be causing this... Is anything showing up in the browser console? If there is, it's probably not going to be very useful until #50 is addressed. Maybe there's a conflict with another script?

**Comment by Lotheric** [comment]
It works with violentmonkey, same script version, same os/browser/other extensions.
I tried with tampermonkey as the only extension in private tab, doesn't work.
I tried disabling all my scripts in TM except yours, doesn't work.

**Comment by Lotheric** [comment]
I installed Tampermonkey Beta v4.14.6143 from the Chrome Web Store (and disabled my other TM extension from the Opera Addon Store) and your script works in it.

**Comment by Lotheric** [comment]
VM181:69 Syntax error @ "MB: Enhanced Cover Art Uploads"!
##########################
JSHINT output:
##########################

SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at <anonymous>:4:80
    at Object.t [as F_c] (<anonymous>:3:191)
    at Object.E_u (<anonymous>:4:244)
    at eval (eval at exec_fn (:2:115), <anonymous>:67:477)
    at Object.create (eval at exec_fn (:2:115), <anonymous>:69:193)
    at c (eval at exec_fn (:2:115), <anonymous>:7:231)
    at <anonymous>:4:80
    at i (eval at exec_fn (:2:115), <anonymous>:5:165)
    at eval (eval at exec_fn (:2:115), <anonymous>:5:292)
    at <anonymous>:13:99
    at HTMLDocument.v (<anonymous>:13:118)
eval @ VM181:69
VM181:69 Uncaught SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at <anonymous>:4:80
    at Object.t [as F_c] (<anonymous>:3:191)
    at Object.E_u (<anonymous>:4:244)
    at eval (eval at exec_fn (add-cover-art:2), <anonymous>:67:477)
    at Object.create (eval at exec_fn (add-cover-art:2), <anonymous>:69:193)
    at c (eval at exec_fn (add-cover-art:2), <anonymous>:7:231)
    at <anonymous>:4:80
    at i (eval at exec_fn (add-cover-art:2), <anonymous>:5:165)
    at eval (eval at exec_fn (add-cover-art:2), <anonymous>:5:292)
    at <anonymous>:13:99
    at HTMLDocument.v (<anonymous>:13:118)

**Comment by ROpdebee** [comment]
Huh. I'll try and figure out what's going on, but this sounds more like a TM issue than an issue with this script, seeing as it works on other engines just fine.

This is perhaps a bit of a far-fetched question, but the installed script does look like this screenshot, right? One long line of code?
<img width="1005" alt="Screenshot 2021-09-26 at 01 50 38" src="https://user-images.githubusercontent.com/15186467/134788677-2afa14db-0d1b-4487-8b6f-58f5f1a4e460.png">

(reason I'm asking is that since it's complaining about an unexpected `<` it might have somehow happened that an uncompiled version with JSX was installed instead)

**Comment by Lotheric** [comment]
Yup! https://i.imgur.com/6NddXMa.png

I think I'll move all my scripts to TM Beta and see if everything works. Don't spend too much time on this :)

**Comment by ROpdebee** [comment]
You could try fully deleting the script and reinstalling, maybe somehow something got messed up in the installation. If that still doesn't work, my bet would be on a bug in either Opera or TM for Opera, because it seems highly unlikely that the script contains a real syntax error (it's been processed by multiple tools and works on all other userscript engines).

If you don't mind, I'm going to close this issue because I don't think there's much that can be done from my side, and you can work around it with a different userscript engine. Feel free to reopen if you've got more information though :)

**Comment by Lotheric** [comment]
I removed the script completely and reinstalled it and now it works in the Opera TM extension (wtf lol). I use a TM feature with Google Drive sync to sync my scripts from the cloud. I suspect at some point something was problematic with script sync. Anyway, problem solved :)

**Comment by ROpdebee** [comment]
Very peculiar :) Maybe a [cosmic ray](https://en.wikipedia.org/wiki/Cosmic_ray#Effect_on_electronics) 😅
