### ISSUE TITLE
[MB: Enhanced Cover Art Uploads] Add support for Bugs!

### ISSUE THREAD

**Issue by Maxr1998** [ROpdebee/mb-userscripts#547]
[Bugs!](music.bugs.co.kr) is a Korean music streaming and purchase site. Provides very high-quality cover arts, good alternative to Melon.

[Example page](https://music.bugs.co.kr/album/4078166). The `og:image` tag contains a link to the cover art (https://image.bugsm.co.kr/album/images/500/40781/4078166.jpg), for the highest quality the `500` can be replaced with `original`: https://image.bugsm.co.kr/album/images/original/40781/4078166.jpg.

**Comment by Maxr1998** [comment]
Thanks for the quick implementation!

Unfortunately, it seems like it broke after a short while. Could you look into it?

**Comment by ROpdebee** [comment]
The example release you linked appears to work for me, as well as some other albums I found on the main page.

Do you have an example of a release that no longer works?

**Comment by Maxr1998** [comment]
I realized it's not really an issue with the userscript, but device related. I'm using the script with Kiwi Browser on Android, and it uses the mobile m.bugs.co.kr site there when fetching the album art.

Unfortunately, the `og:image` tag is slightly broken on the mobile site, since it omits the protocol part of the URL:

```html
<meta property="og:image" content="//image.bugsm.co.kr/album/images/120/40797/4079793.jpg"/>
```

This causes the following error in script:

```
mb_enhanced_cover_art_uploads] Failed to fetch or enqueue images TypeError: Failed to construct 'URL': Invalid URL
    at userscript.html?name…f0c3a3e30:106255:18
```

To work around this issue, you could either hardcode a useragent when fetching the site or handle a missing protocol by prepending it manually.

**Comment by ROpdebee** [comment]
Thanks for debugging this. I've pushed a potential fix in #581 but I'm unable to test this on a mobile device without lots of hassle, so it'd help a lot if you could try out the preview version in https://github.com/ROpdebee/mb-userscripts/pull/581#issuecomment-1272587335 to see if the fix works.

**Comment by Maxr1998** [comment]
Unfortunately not. The image URL in the meta tag uses image.bugsm.co.kr as the domain, whereas the site URL is either music.bugs.co.kr or m.bugs.co.kr. The image URL on the mobile site isn't really relative, just broken due to the missing protocol, unfortunately.

**Comment by ROpdebee** [comment]
It's a [protocol-relative URL](https://en.wikipedia.org/wiki/URL#Protocol-relative_URLs), which says "use the protocol of the document's URL". Entering
```js
new URL('//image.bugsm.co.kr/album/images/120/40797/4079793.jpg', 'https://music.bugs.co.kr/album/4078166').href
```
in my console results in `https://image.bugsm.co.kr/album/images/120/40797/4079793.jpg`.

Did you try it? Because it's odd that it wouldn't fix the issue. (If it doesn't, I'll of course fix it in another way)

**Comment by Maxr1998** [comment]
TIL protocol-relative URLs exist. Thanks for the explanation. I tried it earlier and it failed (because it couldn't find the meta tag element, I think?). I got that error again just now, but after forcibly reloading the page it finally worked. Strange. Maybe some network or caching issue on my end.

Thus, I think your fix can be merged.
