### ISSUE TITLE
MB may upload empty images to CAA when added with ECAU

### ISSUE THREAD

**Issue by ROpdebee** [ROpdebee/mb-userscripts#582]
I had noticed this a few months ago but thought it was related to a buggy FF nightly version, since it disappeared when I upgraded:
https://chatlogs.metabrainz.org/libera/musicbrainz/2022-07-20/?msg=5033103&page=1
https://chatlogs.metabrainz.org/libera/musicbrainz/2022-07-20/?msg=5033175&page=1

In short: Occasionally, when uploading images through ECAU, the upload will throw a generic error (images won't be uploaded). Looking into the network requests it turns out that MB is uploading 0-byte images. However, the uploader previews are shown correctly, so ECAU is correctly sending images to MB. Retrying the upload after it fails without reloading the page doesn't fix the issue, although a page reload often does.

I thought it was fixed by upgrading FF, but I haven't been actively uploading cover art for the last few months, so my experience wasn't representative. However, @hibiscuskazeneko has a [very similar issue](https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/107?u=ropdebee), so it may not have been fixed after all. It's unlikely to be related to CAA 429 issues, as mentioned in that post, since those 429 errors appear to relate to coverartarchive.org, while to my knowledge the uploads hit archive.org directly.

Really unsure what might be causing this, and it looks like it might be very difficult to debug. However, my gut feeling is that this may have to do with garbage collection of the image data. We're not holding a reference to the image data in the script after we've sent it to MB, so possibly, the [object that we produce via `cloneInto`](https://github.com/ROpdebee/mb-userscripts/blob/a5bfdb439ed2bcc631af35b2b03a7f5a3cce2696/src/mb_enhanced_cover_art_uploads/form.ts#L27) relies on a weak reference to the original, which is garbage-collected by the time the image needs to be uploaded, and the resulting data is thus empty.

Some further experimentation is necessary to determine whether that's the true cause though. It may be possible to set up a test scenario that behaves in a similar way, force FF to do a garbage collection pass, and see whether the cloned object survives it.

@hibiscuskazeneko can you confirm that the issue you're facing is happening on Firefox? If so, it's probably the same.

**Comment by HibiscusKazeneko** [comment]
I haven't noticed what you're describing. What I've been seeing is the image upload fails before there's a chance to create an edit.

**Comment by ROpdebee** [comment]
Maybe I didn't describe the issue properly. It's indeed not creating an edit, it fails before that. What happens is when I start the upload with multiple images in the queue (sometimes even just one), the upload fails seemingly randomly. It uploads the first images fine, but then the progressbar jumps from 0% to 90% instantly and I get the error message and the whole thing gets cancelled. If I then start the upload again, it continues jumping from 0% to 90% instantly and the error keeps appearing. Is that what you're experiencing too?

**Comment by HibiscusKazeneko** [comment]
Yes. That's exactly it. Most of the time I'm only uploading 1 image when I see it, but I have seen it with sets of 2 or more.

**Comment by ROpdebee** [comment]
Has anything changed in your setup before this problem started appearing? E.g. browser upgrades, Violentmonkey/Tampermonkey upgrades?

**Comment by HibiscusKazeneko** [comment]
I think I had the same problem on Chrome with Tampermonkey prior to switching to Firefox with Violentmonkey, but it's been so long now my memory is hazy.

**Comment by ROpdebee** [comment]
Some more observations after having edited and uploaded a bunch of cover art recently:
- Happens a lot on larger images, perhaps less often on smaller ones (maybe confirmation bias though)
- The longer you wait to submit the image, the more likely it becomes that it fails in this way, especially if you switch to another tab in the meantime.
- Submitting immediately doesn't seem to fail often.

My gut feeling is still that something somehow unloads the image content that is supposed to get uploaded, possibly to reduce memory consumption.

**Comment by ROpdebee** [comment]
@HibiscusKazeneko if you're still facing this issue, could you test out the fix in https://github.com/ROpdebee/mb-userscripts/pull/687#issuecomment-1633092676 to check if it's effective? It seems to be fixing the issue for me.
