### ISSUE TITLE
'Import from Bandcamp' button missing

### ISSUE THREAD

**Issue by LaHaine** [ROpdebee/mb-userscripts#646]
This is with firefox 111.0.1 on Ubuntu 22.04 with tampermonkey 4.18.1 and the MB: Enhanced Cover Art Uploads script version 2022.11.6. The button 'Import from Bandcamp' is missing on a musicbrainz cover art page. 

Same versions of the script and extension work fine in firefox 111.0 on Ubuntu 18.04.

**Comment by ROpdebee** [comment]
Does this happen on all releases or just some? Anything useful in the browser's console logs?

**Comment by LaHaine** [comment]
I have tried on several pages that have the bandcamp link and should get the button. Not one had it. Here's the multi-process console log from two of those.
![Bildschirmfoto vom 2023-04-04 19-42-53](https://user-images.githubusercontent.com/2370832/229874717-a273e7d3-6532-4638-b79d-e66ba0fcce97.png)
![Bildschirmfoto vom 2023-04-04 19-43-29](https://user-images.githubusercontent.com/2370832/229874724-ca3da775-adb0-4a3c-8575-ab9e5b30a5a0.png)

**Comment by LaHaine** [comment]
Oh, I have removed and reinstalled the userscript and it is working again.

**Comment by LaHaine** [comment]
Could this be a problem with Firefox Sync? I have syncing add-ons enabled

**Comment by ROpdebee** [comment]
No clue. Did the script load properly on the cover art upload pages, or did it not load anywhere at all?

In any case, since the problem was fixed by a reinstall, I'll go ahead and close this issue. However, if it reappears often, feel free to reopen and we can diagnose a bit more.
