### ISSUE TITLE
ECAU: add button for importing thumbnail from YouTube

### ISSUE THREAD

**Issue by UltimateRiff** [ROpdebee/mb-userscripts#722]
I think adding a button for importing YouTube thumbnails would be a great addition, as I do a lot of work adding music videos to the database~

currently, you can just paste into the URL box, but that's perhaps an extra step which isn't necessary. (I'm not sure if this needs to be part of #394 or not, but I figure it's better to have too many issues than not enough... lol)

**Comment by ROpdebee** [comment]
Could you provide an example of a release?

**Comment by UltimateRiff** [comment]
here's one with cover art already added, but if you need one without artwork, I can find or add one~
https://musicbrainz.org/release/e241f35d-1390-4d9f-a4fe-778beeeba3c6
