### ISSUE TITLE
MB: Enhanced Cover Art Uploads has stopped working

### ISSUE THREAD

**Issue by n-99** [ROpdebee/mb-userscripts#738]
Whatever changed must've happened today. The cover art upload screens now look like they do without the script, even when clicking on "Add cover art".

**Comment by ROpdebee** [comment]
What browser and userscript manager are you using? Have you tried reinstalling the script to see if that fixes it? Is anything being logged in the browser console?

**Comment by n-99** [comment]
Firefox 115.0b9 (64-bit), Latest Tampermonkey. Reinstalling the script fixed it, but it's weird, since I didn't change anything before.

**Comment by ROpdebee** [comment]
Thanks for the info. My guess is that it has something to do with the Tampermonkey update. A similar issue was reported in the [community forums](https://community.metabrainz.org/t/ropdebees-userscripts-support-thread/551947/145?u=ropdebee) last week, where reinstalling the script also fixed the issue.
