### ISSUE TITLE
[Enhanced Cover Art Upload] rateyourmusic broken?

### ISSUE THREAD

**Issue by psychoadept** [ROpdebee/mb-userscripts#756]
I've successfully used this with Bandcamp, DIscogs, Amazon, and Deezer, but RYM is giving me this error message. The link is not recognized automatically, either. I am logged in, but even so I have to jump through hoops to get to the artwork manually so that's probably related.

![vivaldi_HYjVBXzQaS](https://github.com/ROpdebee/mb-userscripts/assets/10135275/df6f97bc-6ba6-455d-9f91-0c5566c403cf)

Here's the MB page: https://beta.musicbrainz.org/release/6cacebb4-e212-46c6-84fa-7f644704d237/cover-art

**Comment by ROpdebee** [comment]
#785 will fix the script to recognise those RYM URLs. However, RYM support might be broken for the reasons mentioned there, so YMMV.

**Comment by ROpdebee** [comment]
If RYM support is still broken for you after this patch (e.g., HTTP error 403), feel free to open a new issue report 🙂
