### ISSUE TITLE
Failed to process seeded cover art parameters: seedParameters.entries() is not iterable

### ISSUE THREAD

**Issue by liftarn** [ROpdebee/mb-userscripts#773]
When I clock on cover art I get the message
"Failed to process seeded cover art parameters: seedParameters.entries() is not iterable"
If I click on the source it gets imported correctly. Interestingly on my other computer it works correctly.

**Comment by kellnerd** [comment]
> When I clock on cover art

Can you expand on this please, I don't know which workflow you are using here on which website and for which cover art source?

> Interestingly on my other computer it works correctly.

Without knowing the difference between your computers it is hard to help you here.

**Comment by ROpdebee** [comment]
What browser (Firefox/Chrome/…) and userscript engine (Tampermonkey/Violentmonkey/Greasemonkey/…) are you using? Can you upgrade them to the latest version and check whether the problem persists?

NB: If it's Firefox, it might be related to https://github.com/violentmonkey/violentmonkey/issues/1213 which was diagnosed as a Firefox bug involving Xrays and iterators.

**Comment by ROpdebee** [comment]
I managed to reproduce this with Greasemonkey on Firefox. The `2024.7.27` version released in #784 should fix this issue.
