### ISSUE TITLE
Failed to fetch or enqueue images: HTTP error 403

### ISSUE THREAD

**Issue by Fabe56** [ROpdebee/mb-userscripts#798]
Hi,

Stated with MB: Enhanced Cover Art Uploads version 2024.8.27, appears to be to the same as issue #758 

Thanks ;)

**Comment by dvirtz** [comment]
Works by replacing QUERY_SHA256 with `c7033a9fd1facb3e69fa50074b47e8aa0076857a968e6ed086153840e02b988a`
