### ISSUE TITLE
Apple Music: Fetch original file format

### ISSUE THREAD

**Issue by ROpdebee** [ROpdebee/mb-userscripts#80]
IMU maximises all Apple Music/iTunes covers to a PNG version. However, the source image might not be a PNG. We should add an exception to the maximisation so that we don't unnecessarily consume more bandwidth and storage for a "lossless" version of a lossy source.

For Apple Music, we should be able to determine whether the source image is a JPEG through its URL, see https://beta.musicbrainz.org/edit/81901201. However, old iTunes-style cover art URLs don't contain that filename. The only way to still get those links, AFAIK, is through the old iTunes API. However, a-tisket still uses this old iTunes API, so seeding covers from there will always lead to a PNG unless we skip maximising altogether, which doesn't seem like the right solution. I also doubt we can determine the correct Apple Music URL from an iTunes cover URL. Instead, we should let the a-tisket seeder seed the Apple Music/iTunes release URL which can get processed by the Apple Music provider to determine the Apple Music cover art URL, which then has the original filename through which we can identify the original file format.

All of that is possible, but we should be very careful with _cached_ a-tisket pages. If we seed the release URL itself, the provider will grab the current cover art, even though the cached page may display old cover art which was replaced. So for cached pages, we should fall back to seeding the original cover art URL.

For any direct iTunes cover art links where we cannot or should not use the Apple Music release page to find the Apple Music cover art URL, we should maybe use JPEG images by default instead of PNG.

**Comment by ROpdebee** [comment]
Many thanks for the detailed write-up!

> Is this one extra generation of (arguably imperceptible) rounding errors acceptable?

Personally, I'm not sure. The extreme digital archivist in me says "unacceptable", but the realist says that the costs vastly outweigh the benefits. I've seen plenty of huge PNGs served by Apple, some going up to 30MB, uploading those takes quite a while even on a decent-ish connection, and takes up a lot of unnecessary storage space at the Internet Archive/Cover Art Archive. If it was a question of "original or smaller with imperceptible differences" I'd probably prefer original, but since we don't have access to the original (as far as I know), using the smaller JPEG seems like the better option if the source is also a JPEG.

**Comment by david-russo** [comment]
Certainly, if we could get the original and avoid an extra generation entirely (lossy _or_ lossless) that would be the ideal from a quality and storage perspective. I'm super sympathetic to Extreme Digital Archiving, but the cost of the diminished returns in these cases seem unjustifiably high. (Yet this doesn't stop my inner archivist from trying to make me feel guilty about it.)

**Comment by kellnerd** [comment]
https://github.com/qsniyg/maxurl/issues/962

Apparently someone has found a way to get the Apple source images, I checked a few albums with https://artwork.themoshcrypt.net/ and the `source` JPEGs (HD Source) were smaller than the blown-up `99999x0w-100.jpg` JPEGs which we are currently using. Probably these are indeed the untouched original images.

**Comment by ROpdebee** [comment]
[URL transformation](https://www.reddit.com/r/deemix/comments/oujwf0/comment/h76pe9k/)
